esphome:
  name: ggreg20v3-sensor-node

# adjust for your board: ESP32 / Raspberry Pi Pico W / ESP8266
esp8266: 
  board: nodemcuv2

# Local component setup
#external_components:
#  - source:
#      type: local
#      path: ./my_components/
#    components: [ggreg20_v3]

# GitHub component setup
external_components:
  - source:
      type: git
      url: https://github.com/iotdevicesdev/esphome_external_components 
      ref: main 
    components: [ggreg20_v3] 

logger:
...

api:
...

ota:
  - platform: esphome
    password: "........."
  
wifi:
  ssid: "......."
  password: "......"

  ap:
    ssid: "...... Fallback Hotspot"
    password: "........"

captive_portal:

ggreg20_v3:
  id: ggreg
  
  # Pin configuration for Active-Low operation (default)
  pin:
    number: GPIO4
    mode: INPUT      # No pullup - GGreg20_V3 manages output
    inverted: true   # Read LOW as logical "1" (active state)
  
  # Interrupt logic: 0 = Active-Low (default), 1 = Active-High
  int_logic: 0
  
  # Measurement settings
  measurement_period: 60    # seconds (minimum 10)
  dead_time_us: 190        # microseconds (0-1000)
  
  # Calibration factors (adjust for your specific sensor)
  dose_power_factor: 0.00378     # CPM to µSv/h conversion for J305
  equivalent_dose_factor: 0.00332 # CPM to equivalent µSv/h conversion for J305

  # Sensor definitions (REQUIRED)
  radiation_power:
    name: "Radiation Power"
  equivalent_dose:
    name: "Radiation Equivalent Dose"
  total_dose:
    name: "Total Accumulated Dose"
  cpm:
    name: "Radiation CPM"
  count:
    name: "Pulse Count"
  status:
    name: "Sensor Status"